deislabs/spiderlightning

- README.md
Assuming you didn't mean to refer to storage queues, of course.
> Storage Bus -> Service Bus in Readme.md

- build/azure-pipeline/workflow-pr.yml
> adding cache to az pipeline

- docs/primer.md
Signed-off-by: Radu Matei <radu.matei@fermyon.com>
> Fix a few typos in the documentation

- build/azure-pipeline/workflow-pr.yml
> temporarily removing windows from our matrix of pipelines

- examples/README.md
To add to #166, this additional `README.md` in the `examples` folder explains how to create the required Azure resources.
> explain how to create Azure resources

- crates/pubsub/Cargo.toml
> organized pubsub toml like the others capability tomls

- examples/README.md
This **adapts** examples `README.md` for what had been documented with #168 for issue #166 from local environment variables **to Azure App Configuration**
> convert examples README for Azure App Configuration

- crates/common/src/lib.rs
- crates/kv/src/implementors/azblob.rs
- crates/lockd/src/implementors/etcd.rs
- crates/mq/src/implementors/azsbus.rs
- crates/pubsub/src/implementors/apache_kafka.rs
- crates/runtime-configs/src/lib.rs
- examples/configs-demo/usersecrets_slightfile.toml
> renaming legacy var names

- README.md
- docs/service-implementation-101.md
> added service implementation 101 doc

- Cargo.lock
- crates/common/Cargo.toml
- crates/events/Cargo.toml
- crates/http-handler-macro/Cargo.toml
- crates/http/Cargo.toml
- crates/runtime-configs/Cargo.toml
- tests/http-test/Cargo.lock
> removing unused dependencies

- crates/kv/src/implementors/azblob.rs
- crates/lockd/src/implementors/etcd.rs
- crates/mq/src/implementors/azsbus.rs
- crates/pubsub/src/implementors/apache_kafka.rs
- crates/runtime-configs/src/lib.rs
- examples/configs-demo/usersecrets_slightfile.toml
closes #191, which was brought up by #183.
> added config helper fxn

- .github/workflows/ci.yaml
- Cargo.lock
- Makefile
- docs/primer.md
- slight/Cargo.toml
- slight/src/commands/run.rs
- slight/src/commands/secret.rs
- slight/src/lib.rs
- slight/src/main.rs
- src/lib.rs
- src/sdk/mod.rs
- tests/configs-test/usersecrets_slightfile.toml
the start of an sdk/`slight_lib` to be used by https://github.com/deislabs/containerd-wasm-shims ~ pretty much just exposes the `handle_run` and `handle_secret` that are visible to the cli.
addresses / closes #55 — let me know what you think!
> start of an sdk/slight_lib

- docs/service-implementation-101.md
~just a couple of things I noticed during the brown bag meeting yesterday.
> fixing typos in the service implementation 101 doc

- README.md
> adding more resources on the contributing section of the README

- crates/http-api/src/lib.rs
- crates/http/src/lib.rs
> fixing clippy issue on main

- Cargo.lock
- Makefile
- slight/Cargo.toml
- slight/src/cli.rs
- slight/src/commands/add.rs
- slight/src/commands/mod.rs
- slight/src/commands/new.rs
- slight/src/lib.rs
- slight/src/main.rs
- templates/c/Makefile
- templates/c/slightfile.toml
- templates/c/src/main.c
- templates/rust/Cargo.toml
- templates/rust/slightfile.toml
- templates/rust/src/main.rs
closes #118 
here is an example of creating a new c slight project and running it:
here is an example of creating a new rust slight project and running it:
> added `new` command

- .github/workflows/release.yml
- Makefile
- README.md
- install.ps1
- install.sh
> created release.yml + installation scripts for easy install (inspired by rust and homebrew) + updated readme w/ install instructions

- docs/slightfile-design.md
You can view the file [here](https://github.com/danbugs/spiderlightning/blob/danbugs/config-design-doc/docs/slightfile-design.md).
> slightfile-design doc

- README.md
- docs/slightfile-design.md
> updating README getting started exp + other small doc changes

- Cargo.lock
- crates/events-api/Cargo.toml
- crates/events-api/src/lib.rs
- crates/events/Cargo.toml
- crates/events/src/lib.rs
- examples/watch-demo/simulate.py
> fix(events): added async to events cap

- install.sh
> fixed install script on MacOS

- Cargo.lock
- crates/mq/Cargo.toml
- crates/mq/src/implementors/azsbus.rs
- crates/mq/src/providers/azure.rs
> chore(mq): update azure service bus dependency

- .github/workflows/ci.yaml
- Makefile
> no longer using brew to install redis on linux

- proposals/proposal-template.md
- proposals/slightfile-v0.2.0-proposal.md
> moved proposals to a proposals folder and created a proposal template

- README.md
> update README repo structure

- examples/http-client-demo/src/main.rs
- examples/http-server-demo/Cargo.lock
> small fix on http-client-demo

- examples/http-server-demo/src/main.rs
Some small fixes to the http-server-demo:
* Avoid usage of `unwrap` when something goes wrong, instead return proper errors
* handle_bar: given no body is returned, the HTTP status code should be 204 instead of 200. This prevents `curl` from being stuck
* handle_foo: return HTTP status 200 when everything is fine, instead of 500
> chore: small cleanup of http-server-demo

- Cargo.lock
- Cargo.toml
- slight/Cargo.toml
> Fix: bump slight version to 0.3.0

- README.md
> Docs: modifies README

- .github/workflows/ci.yaml
> CI: Use a seperate job to run rustfmt

- Cargo.lock
- Cargo.toml
- crates/keyvalue/Cargo.toml
- crates/messaging/Cargo.toml
Some minor changes to bump version of the azure deps
> Chore: update deps

- .devcontainer/setup.sh
> Fixes bug reported in #402

- Cargo.lock
- Cargo.toml
- README.md
- templates/rust/Cargo.toml
> bump to v0.5.1
