build/azure-pipeline/workflow-pr.yml
I've noticed that, in avg, it takes 17 mins to execute `make improve` on windows machines. Considering that we are running both `make improve` and unittests on GH action, there is no need to run them again in our integration pipeline. This PR removes them, and hopefully will make our integration pipeline faster to finish. 
=> feat: Removed check and unittests from az pipeline

crates/runtime/src/lib.rs
We are no longer using `config` in `Builder` anymore because #85 adds configuration capability to SpiderLightning that can take care of resource configurations. This PR removes this field from `Builder`. 
=> refactor: removed unused config in Builder

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/setup.sh
First stage for #166 - adding a `.devcontainer` setup.
The configuration is mainly based on the [GitHub Codespaces Rust example](https://github.com/codespaces-examples/rust).
It is comprised of a
- Ubuntu 22.04 base image
- basic Rust and Cargo components to allow development for this project within a Codespace
- required `wit-bindgen-cli` and Rust `wasm32-wasi` target
- basic Visual Studio Code extensions for C and Rust development within a Codespace
=> adding a devcontainer

README.md
Consistently use "SpiderLightning" and fix grammatical issues.
=> Grammar and consistency fixes in the readme

Cargo.lock, crates/kv/Cargo.toml, crates/kv/src/implementors/azblob.rs, crates/kv/src/lib.rs, crates/kv/src/providers/azure.rs, tests/kv-test/src/main.rs
Besides bumping up the version of azure blob storage to `0.5`, this PR also deletes one kv test in the integration test. It deletes the last bits that test to delete a key that doesn't exist in the container. Since AWS dynamodb and azure blob storage have different semantics over this operation, one silently passed and the other throwed an error. Before we decide to go either way, I will remove the test for now. 
=> chore: update azure blob version to 0.5

crates/common/src/lib.rs, crates/http/src/lib.rs
The comment that explained why there was a `block_on` on http body parsing was no longer applicable, since #175 removed the lock on store and instance, instead creates them for each http request. 
=> fix(http): Removed block_on on http body parsing

crates/common/src/lib.rs, crates/http-api/src/lib.rs, crates/http-handler-macro/src/lib.rs, crates/http/src/lib.rs, crates/runtime-configs/src/implementors/usersecrets.rs, crates/runtime-configs/src/lib.rs, crates/runtime/src/lib.rs, slight/src/commands/run.rs, slight/src/commands/secret.rs, src/core/secret.rs, tests/configs-test/usersecrets_slightfile.toml, tests/integration.rs
In library design, it is more versatile to use `AsRef<Path>` to abstract any path types. Thie allow the caller to path `Path`, `PathBuf`, `&str` or `String`.
=> feat: change path of type `&str` to type `AsRef<Path>`

build.rs
added a better error message to deal with the case that wasm32-wasi target isn't installed when building
=> feat: better error message for missing `wasm32-wasi 

slight/src/commands/new.rs
This PR makes the error messages for `slight new` command better in these cases:
1. a version that's not in the releases is given
2. there exists a file/directory of the same name
3. the project name is c or rust
#225
=> feat(slight): better error message for slight new command

.github/workflows/ci.yaml, Makefile, build/azure-pipeline/workflow-pr.yml, crates/kv/src/implementors/redis.rs, tests/configs-test/usersecrets_slightfile.toml, tests/integration.rs, tests/kv-test/kvredis_slightfile.toml
This PR adds the missing integration tests to the KV Redis resource. In fact, I found a bug in the previous redis implementation #187 that didn't use the `name` parameter in `open` at all. I used it and the key to form a compound key `name:key` which will differentiate one container name from another. 
The integration tests will only be run on UNIX OSs because Redis currently does not support Windows.
=> feat(test): added integration tests for kv redis implementaiton

crates/pubsub/src/implementors/mosquitto.rs, crates/pubsub/src/lib.rs
=> small improvements on the mosquitto implementation

slight/src/commands/run.rs
This closes #161 
When the provided file doesn't exist, we now get:
When the provided file isn't a correct slightfile, we now get:
=> improved error messages when failing to provide a correct slightfile

tests/integration.rs
We are out of an AWS account to run integration tests on. Until we get a new account, we will disable AWS specific integration test. 
=> tests: disabling the aws dynamodb integration test

crates/http-handler-macro/src/lib.rs, crates/http/src/lib.rs, examples/http-demo/src/main.rs, tests/http-test/src/main.rs, wit/http-handler.wit, wit/http-types.wit, wit/http.wit
This PR adds a new error type to the http capability named `http-router-error`. Currently, the http capability and http handler are sharing the same error type. This makes it difficult to differentiate the `http-error` defined in the handler and  the one defined in the http capability. 
One of the benefits of splitting them out is that each HTTP handler function, now, can fully use the imports from its crate mod. For example, the http handler can now say
```rust
let keyvalue = Keyvalue::open("my-container").unwrap();
```
while previously a crate namespace is needed
```rust
let keyvalue = crate::Keyvalue::open("my-container").unwrap();
```
=> feat: renamed router http error to http-router-error

slight/src/commands/add.rs, slight/src/commands/new.rs
With this change, we are adding a check to see if the installed version of slight is the same version of the interface that the user is trying to utilize when running `slight new`, or `slight add`.
=> tied slight version to interface version when using slight add or slight new

Cargo.lock, Cargo.toml, README.md, templates/rust/Cargo.toml
This PR bumps the slight CLI to version 0.4.0. 
Do we have a story of when to bump SpiderLightning capability versions, like wasi-keyvalue? They are still at `v0.1.0` now.
=> Chore: bump slight version to 0.4.0

src/commands/add.rs, tests/src/lib.rs
This PR fixed a few typos in the `Add` command which causes failures to download `http-server` and `http-client` WIT interfaces. 
The issue was that the handle_add function uses kebab name for `http-server` and `http-client` but the `get_interface_downloads_by_name` uses snake name for them. This mismatch causes the function to be unsuable for downloading these two interfaces. 
This PR also adds some tracing statements into the Add command and it looks like this:
In addition, it adds an extra check statement `!resp.status().is_success()` to check whether the request interface returns a status code of success, which prevents users to download non-existing interfaces. Previously they will silently succeed and download interfaces which container "not found" as the only content. Now these …
=> Bug: Fixed typos in `add` command and added integration tests

install.ps1
The team name is incorrect, so the GitHub API request will fail to get the latest release tag, and installation will fail. Changing to correct team name and verified installation using Win10/11
=> Fix team name typo

Cargo.lock, Cargo.toml, crates/http-api/Cargo.toml, crates/http-api/src/lib.rs, crates/http-handler-macro/Cargo.toml, crates/http-server/Cargo.toml, examples/app-demos/restaurant-backend/Cargo.toml, examples/configs-demo/Cargo.toml, examples/distributed-locking-demo/Cargo.toml, examples/http-client-demo/Cargo.toml, examples/http-server-demo/Cargo.toml, examples/keyvalue-demo/Cargo.toml, examples/messaging-consumer-demo/Cargo.toml, examples/messaging-producer-demo/Cargo.toml, examples/multi_capability-demo/Cargo.toml, examples/sql-demo/Cargo.toml, src/commands/run.rs, templates/rust/Cargo.toml, tests/configs-test/Cargo.lock, tests/configs-test/Cargo.toml, tests/http-test/Cargo.lock, tests/http-test/Cargo.toml, tests/keyvalue-test/Cargo.lock, tests/keyvalue-test/Cargo.toml
This PR uses [wit-bindgen-backport](https://github.com/fermyon/wit-bindgen-backport)  to replace the mainline wit-bindgen in order to unblock slight to update to the newest wasmtime. Currently [wit-bindgen-backport](https://github.com/fermyon/wit-bindgen-backport) uses `wasmtime 5.0.0` which is a version older than the latest wasmtime. I opened a PR to bump version up in their repo. As soon as that one merges, I will update slight to `wasmtime 6.0.0` and continue to do this for every major release of wasmtime. 
The end goal is switch back to the mainline wit-bindgen as soon as we support wasm component and the newest WIT syntax. This work is out of scope for this PR.
=> Updated wit-bindgen to fermyon/wit-bindgen-backport and wasmtime to 5

Cargo.lock, Cargo.toml, README.md, templates/rust/Cargo.toml
Prepare for a new release of v0.3.3 to include an update to wasmtime `v5.0.0` using wit-bindgen-backport
=> Chore: Bump to 0.3.3

Cargo.lock, Cargo.toml, Makefile, build/azure-pipeline/workflow-pr.yml, crates/messaging/Cargo.toml, crates/messaging/src/implementors/mod.rs, crates/messaging/src/implementors/natsio.rs, crates/messaging/src/lib.rs, crates/runtime-configs/src/lib.rs, examples/configs-demo/Cargo.lock, examples/distributed-locking-demo/Cargo.lock, examples/http-client-demo/Cargo.lock, examples/http-server-demo/Cargo.lock, examples/keyvalue-demo/Cargo.lock, examples/messaging-consumer-demo/Cargo.lock, examples/messaging-consumer-demo/nats_slightfile.toml, examples/messaging-producer-demo/Cargo.lock, examples/messaging-producer-demo/nats_slightfile.toml, examples/multi_capability-demo/Cargo.lock, examples/sql-demo/Cargo.lock, src/commands/run.rs
=> added NATS - a new implementor for the messaging capability!

Cargo.lock, Cargo.toml, crates/common/src/context.rs, crates/http-api/src/lib.rs, crates/http-handler-macro/src/lib.rs, crates/http-server-macro/Cargo.toml, crates/http-server-macro/src/lib.rs, crates/http-server/src/lib.rs, crates/runtime/src/lib.rs, crates/runtime/src/resource.rs, examples/http-server-demo/Cargo.lock, examples/http-server-demo/Cargo.toml, examples/http-server-demo/src/lib.rs, src/commands/run.rs, tests/build.rs, tests/configs-test/us_slightfile.toml, tests/http-test/Cargo.lock, tests/http-test/Cargo.toml, tests/http-test/src/lib.rs, tests/src/lib.rs, wit/http-server-export.wit, wit/http-server.wit, wit/http-types.wit
This PR switches the WASI command model to [reactor model](https://github.com/WebAssembly/WASI/issues/13#:~:text=A%20Command%20has%20a%20%22main,as%20callbacks%20to%20be%20called.) for wasi-http. The reason for that is in the command model, each exported HTTP handler function would not be able to initialize properly with the WASI stdout because the host will not invoke `_start`. The reactor solves this issue.
1. rust slight applications that use http-server must use `cargo new --lib` to create the rust program, instead of `--bin`. This will create a rust library. In Cargo.toml, the following attribute is needed:
```toml
[lib]
crate-type = ["cdylib"]
```
2. Use slight provided `slight_http_server_macro::on_server_init` macro on top of the router and server setup function.
A rust slight …
=> feat(http-server): Add WASI reactor support to http-server cap

Cargo.lock, Cargo.toml, README.md, templates/rust/Cargo.toml
This PR is to bump the slight version to v0.4.1 to include the template updates from #367.
=> chore: bump to v0.4.1

Cargo.lock, Cargo.toml
Just bump the version of wasmtime to `7.0.0` and to the newest wit-bindgen-backport.
=> Chore: bump wasmtime to 7.0.0

Cargo.lock, crates/blob-store/Cargo.toml, crates/blob-store/src/container.rs, crates/blob-store/src/implementors/aws_s3.rs, crates/blob-store/src/implementors/azblob.rs, crates/blob-store/src/implementors/mod.rs, crates/blob-store/src/lib.rs, examples/blob-store-demo/az_blob.toml, src/commands/run.rs, tests/blob-store-test/az_blob.toml, tests/blob-store-test/src/main.rs, tests/src/lib.rs
This PR implements azure blob storage service to the blob-store capability. Notice that the `delete_objects` API is currently not supported in azblob, and thus not implemented. So this will change affect the blob store intergration tests in which I commented out the call to `delete_objects()`. 
This PR does not change or delete azblob service implementation for wasi-keyvalue capability, although blob-store is probably a better place for it to be.
=> feat(blob-store): Add Azure Blob Storage implementation to wasi-blob-store capability

.github/workflows/ci.yaml, build/azure-pipeline/workflow-pr.yml
The current path to openssl.exe on Win agents is `C:\Program Files\OpenSSL`
=> CI: Update Windows CI to the correct openssl path

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/secret.rs, crates/runtime-configs/Cargo.toml, crates/runtime-configs/src/implementors/usersecrets.rs, tests/Cargo.toml, tests/src/lib.rs
The tempdir crate was an out-of-date crate that depends on a older version of `rand`, which causes some issues on our tests when we import `Alphanumeric` from `rand`. 
Since `tempfile` is a crate meant to replace `tempdir`, this PR replaces it to `tempfile`. 
This should make #384 pass the CI
=> fix: remove tempdir crate and replace it with tempfile

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, Makefile, crates/http-api/Cargo.toml, crates/http-server/Cargo.toml, src/cli.rs, src/commands/build.rs, src/commands/buildjs.rs, src/commands/mod.rs, src/commands/new.rs, src/main.rs, templates/js/slightfile.toml, templates/js/src/main.js
This brings:
- SlightJS's build command, and
- a new JS template (which allows users to make use of SlightJS's engine).
PS Also, I had to update wasmtime to 8.0.1 to match Wizer's version.
=> merging slightJS upstream

Cargo.lock, Cargo.toml, crates/http-api/Cargo.toml, crates/http-server/Cargo.toml
this PR updates wasmtime to `v10`
=> chore: bump wasmtime and wit-bindgen to the newest.

install.ps1
The [Update-SessionEnvironment](https://docs.chocolatey.org/en-us/create/functions/update-sessionenvironment) is an implementation of Chocolatey to refresh all the session environment variables. If Chocolatey is not installed, this will fail.  Given that the only variable that is updated is $Path, we only need to refresh that one for the current session, and we can do that manually.
=> Windows installer - Remove Update-SessionEnvironment dependency
